[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pip3.11 install -r requirements.txt --target /app/site-packages"
]

[phases.build]
cmds = ["chmod +x /app/start.sh"]

[variables]
PYTHONPATH = "/app/site-packages:/app/src"

[start]
cmd = "/bin/bash /app/start.sh"
