"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {financialRatios} from '@/lib/research/company-financials.mjs';
import styles from './terminal.module.css';
const number=(v,lang,digits=1)=>Number.isFinite(v)?new Intl.NumberFormat(lang==='en'?'en-US':'es-CL',{maximumFractionDigits:digits}).format(v):'—';
export function useCompanyFinancials(ticker){
 const [attempt,setAttempt]=useState(0),[state,setState]=useState({loading:!!ticker,company:null,error:null});
 useEffect(()=>{if(!ticker){setState({loading:false,company:null,error:null});return}let live=true;const c=new AbortController(),timer=setTimeout(()=>c.abort(),55000);setState({loading:true,company:null,error:null});
 fetch(`/api/public/research/financials?ticker=${encodeURIComponent(ticker)}`,{signal:c.signal}).then(async r=>{const b=await r.json();if(!r.ok)throw Error(r.status===401?'AUTH_REQUIRED':b.error);if(live)setState({loading:false,company:b.company,error:null})}).catch(e=>{if(live)setState({loading:false,company:null,error:e.message})}).finally(()=>clearTimeout(timer));
 return()=>{live=false;clearTimeout(timer);c.abort()};},[ticker,attempt]);
 return {...state,retry:()=>setAttempt(n=>n+1)};
}
export function Watchlist({ticker,language}){
 const en=language==='en',key='bls-research-watchlist-v1';const [items,setItems]=useState([]),[ready,setReady]=useState(false),[error,setError]=useState(false);
 useEffect(()=>{try{const value=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(value))setItems(value.filter(v=>typeof v==='string'&&/^[A-Z][A-Z0-9.-]{0,11}$/.test(v)).slice(0,30))}catch{}setReady(true)},[]);
 function toggle(){const next=items.includes(ticker)?items.filter(t=>t!==ticker):[...items,ticker].slice(-30);try{localStorage.setItem(key,JSON.stringify(next));setItems(next);setError(false)}catch{setError(true)}}
 return <div className={styles.watchlist}><span>{en?'Watchlist':'Seguimiento'}</span>{items.map(t=><Link key={t} href={`/research?ticker=${t}&lang=${language}`} aria-current={t===ticker?'page':undefined}>{t}</Link>)}{/^[A-Z][A-Z0-9.-]{0,11}$/.test(ticker)?<button disabled={!ready} aria-pressed={items.includes(ticker)} onClick={toggle}>{items.includes(ticker)?(en?'Remove company':'Quitar empresa'):(en?'Follow company':'Seguir empresa')}</button>:null}<small>{error?(en?'Browser storage unavailable':'Almacenamiento del navegador no disponible'):(en?'Saved in this browser':'Guardado en este navegador')}</small></div>
}
export function FinancialTerminal({state,language,view='overview',dossier,onView,ticker,documentError}){
 const en=language==='en',c=state.company,[metricId,setMetric]=useState('revenue'),[years,setYears]=useState(5);
 if(state.loading)return <section className={styles.panel} role="status"><h2>{en?'Loading financial history…':'Cargando historia financiera…'}</h2><p>{en?'Documents load separately. You can switch tabs while waiting.':'Los documentos se cargan por separado. Puedes cambiar de pestaña mientras esperas.'}</p></section>;
 if(!c)return <section className={styles.panel} role={state.error?'alert':undefined}><h2>{en?'Financial history':'Historia financiera'}</h2><p>{state.error==='AUTH_REQUIRED'?(en?'Sign in again to retrieve financials.':'Inicia sesión de nuevo para consultar las cifras.'):(en?'Reported figures are not available right now. Documents and your thesis remain separate.':'Las cifras publicadas no están disponibles ahora. Los documentos y tu tesis se consultan por separado.')}</p><button onClick={state.retry}>{en?'Retry financials':'Reintentar cifras'}</button></section>;
 const periods=c.periods.slice(0,years),metric=c.metrics.find(m=>m.id===metricId)||c.metrics[0],points=[...periods].reverse().map(end=>metric.points.find(p=>p.end===end)||{end,value:null});
 const valid=points.filter(p=>Number.isFinite(p.value)),min=Math.min(0,...valid.map(p=>p.value)),max=Math.max(0,...valid.map(p=>p.value)),span=max-min||1;
 const y=v=>170-(v-min)/span*150;
 const exportCsv=()=>{const rows=[['Metric',...periods],...c.metrics.map(m=>[`${m[en?'en':'es']} (${c.currency||'?'})`,...periods.map(end=>m.points.find(p=>p.end===end)?.value??'')])];const text=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${c.ticker}-annual-financials.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const cards=['revenue','netIncome','operatingCash','equity'];
 return <div className={styles.terminal}>

 <div className={view==='overview'?styles.overview:styles.full}>
 <div className={styles.primary}>
 <div className={styles.stats}>{cards.map(id=>{const m=c.metrics.find(m=>m.id===id),p=m?.points.find(p=>p.end===periods[0]);return <div key={id}><span>{id==='netIncome'?(en?'Net income':'Resultado neto'):id==='equity'?(en?'Equity':'Patrimonio'):m?.[en?'en':'es']}</span><strong>{number(Number.isFinite(p?.value)?p.value/1e6:NaN,language)}</strong><small>{c.currency||'—'} {en?'million':'millones'} · {periods[0]?.slice(0,4)||'—'}</small></div>})}</div>
 <section className={styles.panel}><div className={styles.sectionHeading}><h2>{en?'Annual performance':'Evolución anual'}</h2><label>{en?'Metric':'Indicador'}<select value={metricId} onChange={e=>setMetric(e.target.value)}>{c.metrics.map(m=><option key={m.id} value={m.id}>{m[en?'en':'es']}</option>)}</select></label></div>
 {valid.length?<svg className={styles.chart} viewBox="0 0 760 215" role="img" aria-label={`${metric[en?'en':'es']} · ${c.currency} · ${en?'millions':'millones'}`}>
 {[0,.5,1].map(f=>{const v=min+span*f;return <g key={f}><line x1="65" y1={y(v)} x2="750" y2={y(v)} stroke="#293b31" strokeDasharray="3 4"/><text x="55" y={y(v)+4} textAnchor="end">{number(v/1e6,language)}</text></g>})}
 {points.map((p,i)=>{const w=680/points.length,x=70+i*w;return <g key={p.end}><title>{p.end}: {number(p.value,language)} {c.currency}</title>{Number.isFinite(p.value)?<rect x={x+w*.22} y={Math.min(y(p.value),y(0))} width={w*.56} height={Math.max(1,Math.abs(y(p.value)-y(0)))} rx="2" fill={p.value<0?'#d69888':'#bfd59f'}/>:null}<text x={x+w/2} y="195" textAnchor="middle">{p.end.slice(0,4)}</text></g>})}</svg>:<p>{en?'No comparable annual figures for this metric.':'No hay cifras anuales comparables para este indicador.'}</p>}
 <p className={styles.caption}>{en?'Annual reports.':'Informes anuales.'} {c.currency||'—'} {en?'million. Missing data is not zero.':'millones. Un dato ausente no equivale a cero.'}</p></section>
 <section className={styles.panel}><div className={styles.sectionHeading}><h2>{en?'Financial statements':'Estados financieros'}</h2><div className={styles.controls}><label>{en?'Periods':'Períodos'}<select value={years} onChange={e=>setYears(Number(e.target.value))}><option value={3}>3</option><option value={5}>5</option><option value={10}>10</option></select></label><button onClick={exportCsv}>{en?'Export CSV':'Exportar CSV'}</button></div></div>
 <div className={styles.tableScroll} tabIndex={0} role="region" aria-label={en?'Annual financial table':'Tabla financiera anual'}><table><caption>{c.currency||'—'} {en?'million · click a figure to audit its filing':'millones · pulsa una cifra para consultar su informe'}</caption><thead><tr><th scope="col">{en?'Reported metric':'Indicador publicado'}</th>{periods.map(p=><th scope="col" key={p}>{p}</th>)}</tr></thead><tbody>{c.metrics.map(m=><tr key={m.id}><th scope="row">{m[en?'en':'es']}</th>{periods.map(end=>{const p=m.points.find(p=>p.end===end);return <td key={end}>{Number.isFinite(p?.value)?<a href={p.url} target="_blank" rel="noreferrer" title={`${p.form} · ${p.filed} · ${p.concept}`}>{number(p.value/1e6,language)}</a>:'—'}</td>})}</tr>)}</tbody></table></div>
 <p className={styles.caption}>{en?'Latest reported annual values, including restatements. Not a historical point-in-time dataset. No currency conversion.':'Últimas cifras anuales publicadas, incluidas reexpresiones. No es una base histórica punto en el tiempo. Sin conversión de moneda.'} {c.namespace==='ifrs-full'?'IFRS':'US GAAP'}.</p>
 </section></div>
 {view==='overview'?<aside className={styles.side}><section className={styles.panel}><div className={styles.sectionHeading}><h2>{en?'Document coverage':'Cobertura documental'}</h2><button onClick={()=>onView('documents')}>{en?'View':'Ver'}</button></div>{dossier?.sources.length?dossier.sources.map(s=><a className={styles.sourceRow} key={s.id} href={s.url} target="_blank" rel="noreferrer"><strong>{s.form}</strong><span>{s.filedAt||s.acceptedAt?.slice(0,10)}</span><span>{en?'Source':'Fuente'}</span></a>):<p>{documentError?(en?'Documents could not be loaded. Open Documents to retry; financials remain available.':'No se pudieron cargar los documentos. Abre Documentos para reintentar; las cifras siguen disponibles.'):(en?'Retrieving company documents…':'Consultando documentos de la empresa…')}</p>}<p className={styles.caption}>{en?'Selected primary documents; exhibits may contain additional results.':'Documentos principales seleccionados; los anexos pueden contener resultados adicionales.'}</p></section>
 <section className={styles.panel}><h2>{en?'Continue your research':'Continúa tu investigación'}</h2>{[['thesis',en?'Thesis and valuation':'Tesis y valoración',en?'Scenarios, evidence and portfolio exposure':'Escenarios, evidencia y exposición de cartera'],['compare',en?'Compare companies':'Comparar empresas',en?'Margins, cash conversion and reporting periods':'Márgenes, conversión de caja y períodos'],['documents',en?'Read and analyze':'Leer y analizar',en?'Search excerpts and generate a cited report':'Busca extractos y genera un informe con citas']].map(([id,title,detail])=><button className={styles.toolRow} key={id} onClick={()=>onView(id)}><strong>{title}</strong><span>{detail}</span></button>)}<Link className={styles.toolRow} href={`/factorlab?lang=${language}`}><strong>FactorLab</strong><span>{en?'Explore investment factors':'Explorar factores de inversión'}</span></Link></section></aside>:null}
 </div><p className={styles.caption}>{en?'Retrieved':'Consulta'}: {new Date(c.asOf).toLocaleString(en?'en-US':'es-CL')} · <a href={c.sourceUrl} target="_blank" rel="noreferrer">{en?'Structured source data':'Datos estructurados de origen'}</a></p>
 </div>;
}
export function CompanyComparison({company,language}){
 const en=language==='en',[input,setInput]=useState(''),[peer,setPeer]=useState(''),[invalid,setInvalid]=useState(false),state=useCompanyFinancials(peer);
 const companies=[...new Map([company,state.company].filter(Boolean).map(c=>[c.ticker,c])).values()];
 return <section className={styles.panel}><h2>{en?'Compare companies':'Comparar empresas'}</h2><p>{en?'Compare reported annual margins in each company’s own currency. Check the period before drawing conclusions.':'Compara márgenes anuales publicados en la moneda de cada empresa. Revisa el período antes de sacar conclusiones.'}</p><form className={styles.compareForm} onSubmit={e=>{e.preventDefault();const t=input.trim().toUpperCase();if(!/^[A-Z][A-Z0-9.-]{0,11}$/.test(t)){setInvalid(true);return}setInvalid(false);setPeer(t)}}><label htmlFor="peer-ticker">{en?'Company to compare':'Empresa para comparar'}</label><input id="peer-ticker" value={input} onChange={e=>setInput(e.target.value)} placeholder="NKE" maxLength={12}/><button>{en?'Compare':'Comparar'}</button></form>{invalid?<p role="alert">{en?'Enter a valid ticker.':'Escribe un ticker válido.'}</p>:null}{state.loading?<p role="status">{en?'Loading comparison…':'Cargando comparación…'}</p>:null}{state.error?<p role="alert">{en?'Could not load the comparison company.':'No se pudo cargar la empresa para comparar.'} <button onClick={state.retry}>{en?'Retry':'Reintentar'}</button></p>:null}
 <div className={styles.tableScroll}><table><thead><tr><th>{en?'Metric':'Indicador'}</th>{companies.map(c=><th key={c.ticker}>{c.ticker}</th>)}</tr></thead><tbody>{[['name',en?'Company':'Empresa'],['period',en?'Year end':'Cierre anual'],['currency',en?'Reporting currency':'Moneda de reporte'],['netMargin',en?'Net margin':'Margen neto'],['cashMargin',en?'Operating cash / revenue':'Caja operativa / ingresos']].map(([id,label])=><tr key={id}><th>{label}</th>{companies.map(c=>{const ratios=financialRatios(c),v=ratios[id];return <td key={c.ticker}>{id==='period'?c.periods[0]||'—':id==='netMargin'||id==='cashMargin'?(Number.isFinite(v)?`${number(v*100,language)}%`:'—'):c[id]||'—'}</td>})}</tr>)}</tbody></table></div><p className={styles.caption}>{en?'Ratios are calculated from matching annual periods and currency. Missing or inconsistent inputs remain blank.':'Los ratios usan períodos anuales y moneda coincidentes. Los datos ausentes o inconsistentes quedan vacíos.'}</p></section>
}
