'use client';
import {useEffect,useRef,useState} from 'react';
import styles from './terminal.module.css';
const labels={
 es:{relevance:'Relevancia',tone:'Tono',event:'Evento',materiality:'Importancia',evidence:'Tipo de evidencia',relation:'Relación con la tesis',testability:'Prueba propuesta',direct:'Directa',indirect:'Indirecta',unrelated:'Sin relación',unknown:'Sin resolver',positive:'Positivo',negative:'Negativo',mixed:'Mixto',neutral:'Neutral',earnings:'Resultados',guidance:'Perspectivas',financing:'Financiamiento',legal:'Legal / regulatorio',product:'Productos / negocio',management:'Gobierno corporativo',analyst:'Opinión de analista',price:'Movimiento de precio',other:'Otro',high:'Revisar cambio relevante',routine:'Rutinario',context:'Contexto',reported:'Hecho o política reportada',outlook:'Expectativa',risk:'Riesgo hipotético',supports:'Apoyo textual',contradicts:'Contraevidencia',testable:'Contrastable',vague:'Poco específica'},
 en:{relevance:'Relevance',tone:'Tone',event:'Event',materiality:'Materiality',evidence:'Evidence type',relation:'Thesis relationship',testability:'Proposed test',direct:'Direct',indirect:'Indirect',unrelated:'Unrelated',unknown:'Unresolved',positive:'Positive',negative:'Negative',mixed:'Mixed',neutral:'Neutral',earnings:'Earnings',guidance:'Guidance',financing:'Financing',legal:'Legal / regulatory',product:'Products / business',management:'Governance',analyst:'Analyst opinion',price:'Price movement',other:'Other',high:'Review material change',routine:'Routine',context:'Context',reported:'Reported fact or policy',outlook:'Outlook',risk:'Hypothetical risk',supports:'Textual support',contradicts:'Counterevidence',testable:'Testable',vague:'Vague'}
};
const statusText={
 not_configured:['Jev aún no está conectado. La investigación sigue disponible.','Jev is not connected yet. Research remains available.'],
 ready:['Conexión configurada. Evalúa cuando lo necesites.','Connection configured. Run an assessment when needed.'],
 authentication_failed:['La credencial de Jev no fue aceptada.','The Jev credential was not accepted.'],
 rate_limited:['Jev alcanzó su límite temporal. Reintenta más tarde.','Jev reached its temporary limit. Retry later.'],
 unavailable:['Jev no respondió con una evaluación válida.','Jev did not return a valid assessment.'],
 busy:['Hay demasiadas consultas. Reintenta más tarde.','Too many requests. Retry later.'],
 empty:['No hay evidencia elegible para evaluar.','No eligible evidence to assess.'],
 partial:['Evaluación parcial; algunos elementos no se pudieron evaluar.','Partial assessment; some items could not be assessed.']
};
export function JevPanel({kind,language,ticker,scope='stock',watchlist='',dossier,ticket,revisionHash,disabled=false}) {
 const en=language==='en',c=labels[en?'en':'es'];
 const [connection,setConnection]=useState(''),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[question,setQuestion]=useState(''),[filter,setFilter]=useState('all');
 const controller=useRef(null);
 useEffect(()=>{const ac=new AbortController();fetch('/api/research/jev',{signal:ac.signal,cache:'no-store'}).then(r=>r.ok?r.json():null).then(v=>{if(v)setConnection(v.status)}).catch(()=>{});return()=>{ac.abort();controller.current?.abort()}},[]);
 useEffect(()=>{controller.current?.abort();controller.current=null;setResult(null);setBusy(false);setError('')},[ticker,scope,watchlist,dossier?.packetHash,revisionHash,question,disabled]);
 async function run(event){event.preventDefault();if(busy)return;const ac=new AbortController();controller.current=ac;const timer=setTimeout(()=>ac.abort(),95000);setBusy(true);setError('');setResult(null);
  try{const payload=kind==='news'?{kind,scope,ticker,tickers:watchlist.split(',').filter(Boolean)}:kind==='documents'?{kind,dossier,ticket,question}:{kind,revisionHash};const response=await fetch('/api/research/jev',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:ac.signal,cache:'no-store'});const body=await response.json();if(controller.current!==ac)return;if(!response.ok)throw Error(response.status===401?'AUTH_REQUIRED':body.error);setResult(body);if(body.status==='not_configured')setConnection(body.status)}
  catch(e){if(controller.current===ac)setError(e.message)}finally{clearTimeout(timer);if(controller.current===ac){setBusy(false);controller.current=null}}
 }
 const title=kind==='news'?(en?'Jev · news and portfolio review':'Jev · revisión de noticias y cartera'):kind==='documents'?(en?'Jev · find relevant evidence':'Jev · encontrar evidencia relevante'):(en?'Jev · thesis evidence review':'Jev · contraste de tesis');
 const items=(result?.items||[]).filter(r=>filter!=='attention'||r.answers?.materiality?.choice==='high'&&!r.answers.materiality.uncertain&&r.answers?.relevance?.choice==='direct'&&!r.answers.relevance.uncertain).sort((a,b)=>kind==='documents'?Number(b.answers?.relevance?.choice==='direct'&&!b.answers.relevance.uncertain)-Number(a.answers?.relevance?.choice==='direct'&&!a.answers.relevance.uncertain):(b.priority??-1)-(a.priority??-1));
 function exportResult(){const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`bls-jev-${kind}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className={`${styles.panel} ${styles.jevPanel}`} aria-label={title}>
  <h2>{title}</h2>
  <p>{kind==='news'?(en?'Assess each headline for each company. Portfolio review highlights relevant events and orders them by known holding weight.':'Evalúa cada titular por empresa. La revisión de cartera destaca eventos relevantes y los ordena por peso conocido de la posición.'):kind==='documents'?(en?'Ask a specific question to rank selected filing excerpts. Only the displayed excerpts are assessed.':'Haz una pregunta concreta para ordenar extractos del expediente. Solo se evalúan los extractos mostrados.'):(en?'Check saved claims against their linked excerpts and review whether the proposed tests distinguish outcomes.':'Contrasta afirmaciones guardadas con sus extractos vinculados y revisa si las pruebas propuestas distinguen resultados.')}</p>
  <form onSubmit={run}>
   {kind==='documents'?<label>{en?'Research question':'Pregunta de investigación'}<input required maxLength={600} value={question} onChange={e=>{setQuestion(e.target.value);setResult(null)}} placeholder={en?'What evidence describes customer concentration?':'¿Qué evidencia describe la concentración de clientes?'}/></label>:null}
   <button type="submit" disabled={busy||disabled||(kind==='thesis'&&!revisionHash)||(kind==='documents'&&!question.trim())}>{busy?(en?'Assessing evidence…':'Evaluando evidencia…'):(en?'Assess with Jev':'Evaluar con Jev')}</button>
  </form>
  {disabled||kind==='thesis'&&!revisionHash?<p>{en?'Save your thesis changes before reviewing this revision.':'Guarda los cambios de tu tesis antes de revisar esta versión.'}</p>:null}
  <p className={styles.caption}>{en?'Experimental model assessment. Uncertain classifications remain unresolved; confidence is not accuracy or a probability of price gains. Sources and calculations remain independently inspectable.':'Evaluación experimental del modelo. Las clasificaciones inciertas quedan sin resolver; la confianza no es exactitud ni probabilidad de alza. Las fuentes y los cálculos se pueden revisar por separado.'}</p>
  {kind==='thesis'?<p className={styles.caption}>{en?'Runs only when requested. Sends the saved claims and cited excerpts to TypeSafe; does not send your identity, holdings or portfolio values. It does not edit your thesis.':'Se ejecuta solo al solicitarlo. Envía las afirmaciones guardadas y los extractos citados a TypeSafe; no envía tu identidad, posiciones ni valores de cartera. No modifica tu tesis.'}</p>:null}
  {error?<p role="alert">{error==='AUTH_REQUIRED'?(en?'Sign in again to continue.':'Vuelve a iniciar sesión para continuar.'):error==='DOSSIER_EXPIRED'?(en?'Reload the dossier before assessing its evidence.':'Recarga el expediente antes de evaluar su evidencia.'):error==='BUSY'?(en?'Too many requests. Retry later.':'Hay demasiadas consultas. Reintenta más tarde.'):(en?'Assessment unavailable. Retry; your research is preserved.':'Evaluación no disponible. Reintenta; tu investigación se conserva.')}</p>:null}
  {statusText[result?.status||connection]?<p role="status">{statusText[result?.status||connection][en?1:0]}</p>:null}
  {result?.total!==undefined?<p>{result.assessed} / {result.total} {en?'items assessed':'elementos evaluados'} · {en?'Selected':'Seleccionados'}: {result.selected}{result.asOf?` · ${result.asOf.slice(0,19).replace('T',' ')} UTC`:''}</p>:null}
  {result?.items?.length?<>
   <div className={styles.controls}>{kind==='news'?<label>{en?'Show':'Mostrar'}<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{en?'All assessed headlines':'Todos los titulares evaluados'}</option><option value="attention">{en?'Material events to review':'Eventos relevantes para revisar'}</option></select></label>:null}<button type="button" onClick={exportResult}>{en?'Export assessment':'Exportar evaluación'}</button></div>
   <p className={styles.caption}>{kind==='news'?(en?'Up to 60 article–company pairs, distributed across scanned companies; excluded items are not neutral. Review ordering uses stored positive portfolio values, excluding missing values.':'Hasta 60 pares titular–empresa, distribuidos entre empresas consultadas; los elementos excluidos no son neutrales. El orden de revisión usa valores positivos guardados y excluye valores ausentes.'):kind==='documents'?(en?'Up to 24 selected excerpts, first 2,500 characters each; this is not a full filing search.':'Hasta 24 extractos seleccionados, primeros 2.500 caracteres por extracto; no es una búsqueda del documento completo.'):(en?'Uses this saved revision and its document cutoff. Up to eight linked excerpts per claim, first 2,000 characters each; no new filings are fetched.':'Usa esta revisión guardada y su corte documental. Hasta ocho extractos vinculados por afirmación, primeros 2.000 caracteres por extracto; no se consultan documentos nuevos.')}</p>
   <ol className={styles.newsList}>{items.map(r=><li key={r.id}>
    <strong>{r.ticker} · {r.title||r.statement||r.id}</strong>
    {r.companyName?<p>{r.companyName}</p>:null}
    {r.answers?.relevance?.withheldReason==='identity_unconfirmed'?<p>{en?'Company identity is not explicit in this headline. A direct-company classification has been withheld.':'La identidad de la empresa no es explícita en este titular. Se retuvo la clasificación de relación directa.'}</p>:null}
    {r.answers?.materiality?.withheldReason==='opinion_or_price'?<p>{en?'An analyst opinion or price move alone does not establish a fundamental change.':'Una opinión de analista o un movimiento de precio por sí solos no establecen un cambio fundamental.'}</p>:null}
    {r.url?<p><a href={r.url} target="_blank" rel="noreferrer">{en?'Open source':'Abrir fuente'}</a>{r.date?` · ${r.date.slice(0,10)}`:''}</p>:null}
    {r.text?<details><summary>{en?'Assessed excerpt':'Extracto evaluado'}{r.truncated?' · '+(en?'truncated':'recortado'):''}</summary><blockquote>{r.text}</blockquote></details>:null}
    {r.evidence?<details><summary>{en?'Assessed evidence':'Evidencia evaluada'} · {r.evidence.length}/{r.evidenceTotal}</summary>{r.evidence.map((e,i)=><blockquote key={`${e.id}:${i}`}><small>{e.id}</small><br/>{e.text}</blockquote>)}</details>:null}
    {r.answers?<><div className={styles.jevAnswers}>{Object.entries(r.answers).map(([name,a])=><span key={name}><b>{c[name]}</b>: {a.uncertain?(en?'Unresolved':'Sin resolver'):c[a.choice]}{a.uncertain&&a.choice!=='unknown'?` (${en?'tentative':'tentativo'}: ${c[a.choice]})`:''}</span>)}</div><details><summary>{en?'Model probabilities and confidence':'Probabilidades y confianza del modelo'}</summary>{Object.entries(r.answers).map(([name,a])=><p key={name}>{c[name]} · {en?'Confidence':'Confianza'} {Math.round(a.confidence*100)}% · {Object.entries(a.probabilities).map(([k,v])=>`${c[k]} ${Math.round(v*100)}%`).join(' / ')}</p>)}</details><small>{r.model} · {result.rubric}{r.priority!==null?` · ${en?'Known portfolio weight':'Peso conocido en cartera'} ${(r.priority*100).toFixed(1)}%`:''}</small></>:<p>{statusText[r.status]?.[en?1:0]||statusText.unavailable[en?1:0]}</p>}
   </li>)}</ol>{!items.length?<p>{en?'No assessed items meet this filter.':'Ningún elemento evaluado cumple este filtro.'}</p>:null}
  </>:null}
 </section>;
}
