'use client';
import Link from 'next/link';
import {useState} from 'react';
import {PublicSiteHeader} from '@/components/public-shell/public-site-header';
import {publicExample as data,exampleCashBridge} from '@/lib/research/public-example.mjs';
import styles from './example.module.css';
export function PublicExample({language='es'}){
 const en=language==='en',bridge=exampleCashBridge(),[weight,setWeight]=useState(10),[loss,setLoss]=useState(30);
 const fmt=n=>new Intl.NumberFormat(en?'en-US':'es-CL',{maximumFractionDigits:1}).format(n);
 const next=`/research?ticker=MSFT&lang=${language}`;
 return <><PublicSiteHeader initialLanguage={language} /><main className={styles.page} data-no-translate>
  <header><p>{en?'PUBLIC EXAMPLE · NO ACCOUNT':'EJEMPLO PÚBLICO · SIN CUENTA'}</p><h1>Microsoft.<br/>{en?'More cash. More investment.':'Más caja. Más inversión.'}</h1><p>{en?'Historical case · fiscal years ended June 30, 2024 and 2025. Not a current company assessment.':'Caso histórico · ejercicios cerrados el 30 de junio de 2024 y 2025. No es una evaluación actual de la empresa.'}</p></header>
  <section><h2>{en?'01 / What changed':'01 / Qué cambió'}</h2><div className={styles.tableWrap}><table><caption>{en?'Cash bridge · USD millions':'Puente de caja · millones de USD'}</caption><thead><tr><th>{en?'Measure':'Concepto'}</th>{data.years.map(y=><th key={y}>{y}</th>)}<th>Δ</th></tr></thead><tbody>
   {[[en?'Operating cash flow':'Flujo operativo',data.cfo,bridge.cfoChange],[en?'Cash investment in property and equipment':'Inversión en propiedades y equipos',data.capex,bridge.capexChange],[en?'Arithmetic difference':'Diferencia aritmética',bridge.residual,bridge.residualChange]].map(([label,values,change])=><tr key={label}><th>{label}</th>{values.map((v,i)=><td key={i}>{fmt(v)}</td>)}<td>{fmt(change*100)}%</td></tr>)}
  </tbody></table></div><p>{en?'Operating cash grew, but investment grew faster. Their difference fell. That alone does not establish deterioration or mispricing.':'La caja operativa creció, pero la inversión creció más. La diferencia cayó. Eso, por sí solo, no demuestra deterioro ni una acción mal valorada.'}</p>
  <details><summary>{en?'Verify the source and calculation':'Verificar fuente y cálculo'}</summary><p>{data.years.map((y,i)=>`${y}: ${fmt(data.cfo[i])} − ${fmt(data.capex[i])} = ${fmt(bridge.residual[i])}`).reverse().join('. ')}.</p><p>{en?'Locator: Cash Flows Statements. Figures reviewed September 13, 2026.':'Localizador: Cash Flows Statements. Cifras revisadas el 13 de septiembre de 2026.'}</p><a href={data.source} target="_blank" rel="noreferrer">Microsoft · Annual Report 2025 </a></details></section>
  <section><h2>{en?'02 / What would change the thesis':'02 / Qué cambiaría la tesis'}</h2><p>{en?'Question: how much investment maintains the existing business, and how much builds future capacity?':'Pregunta: ¿cuánta inversión mantiene el negocio y cuánta crea capacidad futura?'}</p><p>{en?'Favourable hypothesis: investment produces durable cash generation. Counterargument: recurring reinvestment absorbs the gains. Compare future cash generation, investment and lease commitments.':'Hipótesis favorable: la inversión produce caja duradera. Contraargumento: la reinversión recurrente absorbe las mejoras. Contrastar caja, inversión y compromisos de arrendamiento posteriores.'}</p><p className={styles.note}>{en?'The difference above is not normalized owner earnings or unlevered free cash flow. Maintenance, growth and lease obligations are not reconciled here. No target price is published.':'La diferencia anterior no es caja normalizada del accionista ni flujo libre antes de financiación. Aquí no están conciliados mantenimiento, expansión y arrendamientos. No se publica precio objetivo.'}</p></section>
  <section><h2>{en?'03 / Why position size matters':'03 / Por qué importa el tamaño de la posición'}</h2><p>{en?'Independent arithmetic illustration. These inputs are hypothetical, not forecasts or your holdings.':'Ilustración aritmética independiente. Los valores son hipotéticos, no pronósticos ni tu cartera.'}</p><div className={styles.inputs}><label>{en?'Position weight (%)':'Peso de la posición (%)'}<input type="range" min="0" max="100" value={weight} onChange={e=>setWeight(Number(e.target.value))}/>{weight}%</label><label>{en?'Hypothetical fall (%)':'Caída hipotética (%)'}<input type="range" min="0" max="100" value={loss} onChange={e=>setLoss(Number(e.target.value))}/>{loss}%</label></div><output aria-live="polite">−{fmt(weight*loss/100)}% {en?'of portfolio value':'del valor de la cartera'}</output><p>{en?'Only this position changes; all other positions and cash stay constant. No leverage, fees or trading.':'Sólo cambia esta posición; las demás y la caja quedan constantes. Sin apalancamiento, costos ni operaciones.'}</p></section>
  <section><h2>{en?'Now investigate your own company.':'Ahora investiga tu empresa.'}</h2><p>{en?'Read documents first. Save your thesis and connect your portfolio when ready. Private research requires an account.':'Lee los documentos primero. Guarda tu tesis y conecta tu cartera cuando estés listo. La investigación privada requiere una cuenta.'}</p><Link className={styles.cta} href={`/login?intent=signup&lang=${language}&next=${encodeURIComponent(next)}`}>{en?'Investigate Microsoft':'Investigar Microsoft'} </Link><Link href={`/aurora?lang=${language}`}>{en?'Or explore public valuation':'O explorar la valoración pública'} </Link></section>
 </main></>;
}
