import test from 'node:test';
import assert from 'node:assert/strict';
import * as engine from '../lib/research/filing-engine.mjs';
import {compileDossier} from '../lib/research/dossier.js';

const rows = Array.from({length: 60}, (_, i) => `<tr><td>Operating cash adjustment ${i}</td><td>${i + 1}</td><td>${i + 2}</td></tr>`).join('');
const html = `<h2>CONSOLIDATED STATEMENTS OF CASH FLOWS</h2><p>(In millions, unaudited)</p>
<table><tr><th></th><th colspan="2">Six months ended</th></tr>
<tr><th></th><th>March 28, 2026</th><th>March 29, 2025</th></tr>${rows}
<tr><td>Cash generated by operating activities</td><td>82,627</td><td>53,887</td></tr></table>
<p>Notes to the financial statements follow.</p>`;

test('a cash flow table is never split away from its period, units or title', () => {
 assert.equal(typeof engine.documentStructure, 'function');
 const document = engine.documentStructure(html);
 const chunks = engine.makeChunks(document, 'D1');
 const selected = chunks.filter(c => c.text.includes('82,627'));
 assert.equal(selected.length, 1);
 const table = selected[0];
 assert.equal(table.kind, 'table');
 for (const value of ['CONSOLIDATED STATEMENTS OF CASH FLOWS','In millions','Six months ended','March 28, 2026','March 29, 2025','Operating cash adjustment 0','Operating cash adjustment 59']) assert.ok(table.text.includes(value), value);
 assert.equal(table.table.complete, true);
 assert.equal(table.table.rows, 63);
 assert.ok(!table.text.includes('Notes to the financial statements follow'));
});

test('hidden tables cannot supply visible rows or disturb table boundaries', () => {
 assert.equal(typeof engine.documentStructure, 'function');
 const document = engine.documentStructure(`<ix:hidden><table><tr><td>Invented revenue</td><td>999</td></tr></table></ix:hidden>${html}`);
 const chunks = engine.makeChunks(document, 'D1');
 assert.ok(chunks.every(c => !c.text.includes('Invented')));
 assert.equal(chunks.filter(c => c.kind === 'table').length, 1);
});

test('an interrupted table remains explicitly incomplete rather than becoming normal prose', () => {
 assert.equal(typeof engine.documentStructure, 'function');
 const chunks = engine.makeChunks(engine.documentStructure('<h2>Cash flows</h2><table><tr><td>Operating cash flow</td><td>100</td></tr>'), 'D1');
 const table = chunks.find(c => c.kind === 'table');
 assert.equal(table.table.complete, false);
 assert.ok(!engine.retrieve(chunks, engine.topics[1]).some(c => c.id === table.id));
});

test('legacy plain blocks remain readable without inventing structural provenance', () => {
 const blocks = engine.documentBlocks('<p>Revenue and cash flows.</p>');
 assert.deepEqual(blocks, ['Revenue and cash flows.']);
 const chunks = engine.makeChunks(blocks, 'D1');
 assert.equal(chunks[0].text, 'Revenue and cash flows.');
 assert.equal(chunks[0].table, undefined);
});

test('business overview survives keyword-rich accounting notes and a newer table', () => {
 const overview='We manufacture household appliances and provide installation and repair services to commercial clients. '.repeat(5);
 const annual=engine.makeChunks(engine.documentStructure(`<h2>Item 1. Business</h2><p>${overview}</p><h2>Item 8. Financial Statements</h2>${[0,1,2,3].map(i=>`<table><tr><td>Revenue subscription customer operating income ${i}</td><td>100</td></tr></table>`).join('')}`),'D1');
 const quarterly=engine.makeChunks(engine.documentStructure('<h2>Item 2. Management discussion</h2><p>Revenue declined as customer demand softened in the current quarter. The company attributes this change to lower shipments rather than a change in its accounting policy.</p>'),'D2');
 const sources=['D1','D2'].map((id,i)=>({id,form:i?'10-Q':'10-K',sha256:'a'.repeat(64),acceptedAt:`2026-0${i+1}-15T00:00:00Z`,url:`https://www.sec.gov/Archives/edgar/data/1/${id}.htm`}));
 const dossier=compileDossier({ticker:'ACME',asOf:'2026-03-01T00:00:00Z',sources,chunks:[...annual,...quarterly]});
 const business=dossier.sections.find(s=>s.id==='business');
 assert.ok(business.extracts.some(c=>c.text.includes('household appliances')));
 assert.ok(business.extracts.some(c=>c.text.includes('lower shipments')));
 assert.ok(business.extracts.length<=3);
 assert.equal(business.coverage.roles.find(r=>r.id==='business_overview').status,'selected');
});

test('current product revenue tables reach the business analysis instead of an older segment description',()=>{
 const sources=['D1','D2'].map((id,i)=>({id,form:i?'10-Q':'10-K',sha256:'a'.repeat(64),acceptedAt:`2026-0${i+1}-15T00:00:00Z`,url:`https://www.sec.gov/Archives/edgar/data/1/${id}.htm`}));
 const chunks=[
  {id:'D1:1',kind:'prose',documentSection:'1',blockStart:1,text:'We manufacture household appliances and provide installation and repair services to commercial clients. Our products are sold by independent distributors.'},
  {id:'D1:20',kind:'prose',documentSection:'8',blockStart:20,text:'We manage our operating segments using a regional structure. Segment revenue is evaluated by management at the end of each reporting period.'},
  {id:'D2:2',kind:'prose',documentSection:'2',blockStart:2,text:'Net sales increased primarily due to higher shipments of appliances. Management discusses changes in product demand and service sales during the period.'},
 ];
 for(const title of ['The following table shows disaggregated net sales','The following table shows revenue by product']){
  const table={id:'D2:T10',kind:'table',documentSection:'1',blockStart:10,table:{complete:true,rows:4},text:`${title}\nCurrent | Prior\nDevices | 80 | 60\nServices | 20 | 10\nTotal | 100 | 70`};
  const compile=all=>compileDossier({ticker:'ACME',asOf:'2026-03-01T00:00:00Z',sources,chunks:all}).sections.find(s=>s.id==='business');
  const business=compile([...chunks,table]);
  assert.equal(business.coverage.roles.find(r=>r.id==='segment_economics').chunkId,table.id);
  assert.equal(business.extracts.find(c=>c.id===table.id).text,table.text);
  assert.equal(business.extracts.length,3);assert.ok(business.coverage.characters<=6000);
  const incomplete=compile([...chunks,{...table,table:{...table.table,complete:false}}]);
  assert.equal(incomplete.coverage.roles.find(r=>r.id==='segment_economics').chunkId,'D1:20');
 }
});

test('a bare table heading cannot take an evidence slot from a substantive source', () => {
 const chunks=engine.makeChunks(engine.documentStructure('<h2>CASH FLOWS STATEMENTS</h2>'+html),'D1');
 const selected=engine.retrieve(chunks,engine.topics[1]);
 assert.ok(selected.some(c=>c.text.includes('82,627')));
 assert.ok(selected.every(c=>c.kind==='table'||c.text.length>=100));
});

test('a newer accounting mention does not displace the actual financial risk disclosure',()=>{
 const annual=engine.makeChunks(engine.documentStructure('<h2>Item 1A. Risk Factors</h2><p>We may be unable to refinance our debt at maturity. Loss of liquidity could prevent us from meeting obligations and force us to sell operating assets.</p>'),'D1');
 const quarterly=engine.makeChunks(engine.documentStructure('<h2>Item 1. Financial Statements</h2><p>Debt securities have varying maturities. The fair value measurement technique may use observable market inputs and counterparty credit risk adjustments.</p>'),'D2');
 const sources=['D1','D2'].map((id,i)=>({id,form:i?'10-Q':'10-K',sha256:'a'.repeat(64),acceptedAt:`2026-0${i+1}-15T00:00:00Z`,url:`https://www.sec.gov/Archives/edgar/data/1/${id}.htm`}));
 const dossier=compileDossier({ticker:'ACME',asOf:'2026-03-01T00:00:00Z',sources,chunks:[...annual,...quarterly]});
 const role=dossier.sections.find(s=>s.id==='thesis').coverage.roles.find(r=>r.id==='financial_risks');
 assert.ok(role.chunkId.startsWith('D1:'));
});

test('an oversized statement stays whole and its budget omission is explicit',()=>{
 const large='<h2>CONSOLIDATED STATEMENTS OF CASH FLOWS</h2><table><tr><td>Year ended</td><td>2026</td></tr>'+Array.from({length:200},(_,i)=>`<tr><td>Operating cash adjustment number ${i}</td><td>10000</td></tr>`).join('')+'</table>';
 const chunks=engine.makeChunks(engine.documentStructure(large),'D1');
 const sources=[{id:'D1',form:'10-K',sha256:'a'.repeat(64),acceptedAt:'2026-01-15T00:00:00Z',url:'https://www.sec.gov/Archives/edgar/data/1/D1.htm'}];
 const dossier=compileDossier({ticker:'ACME',asOf:'2026-03-01T00:00:00Z',sources,chunks});
 const cash=dossier.sections.find(s=>s.id==='cash');
 assert.ok(chunks.find(c=>c.kind==='table').text.includes('adjustment number 199'));
 assert.equal(cash.coverage.roles.find(r=>r.id==='cash_flow_statement').status,'budget_limited');
 assert.equal(cash.coverage.excludedOversizedChunks,1);
 assert.ok(cash.extracts.every(c=>!c.text.includes('Operating cash adjustment')));
});

test('capital obligations prefer a maturity disclosure over valuation-method boilerplate',()=>{
 const chunks=engine.makeChunks(engine.documentStructure('<h2>Item 1. Financial Statements</h2><p>Debt securities have varying maturities. The fair value measurement technique may use observable market inputs and counterparty credit risk adjustments.</p><table><tr><td>Fair value</td><td>100</td></tr></table><h3>Term Debt</h3><p>The company has fixed-rate notes with maturities over the next five years. Its principal obligations require annual repayments irrespective of revenue growth.</p>'),'D1');
 const sources=[{id:'D1',form:'10-Q',sha256:'a'.repeat(64),acceptedAt:'2026-01-15T00:00:00Z',url:'https://www.sec.gov/Archives/edgar/data/1/D1.htm'}];
 const cash=compileDossier({ticker:'ACME',asOf:'2026-03-01T00:00:00Z',sources,chunks}).sections.find(s=>s.id==='cash');
 const id=cash.coverage.roles.find(r=>r.id==='capital_obligations').chunkId;
 assert.ok(cash.extracts.find(c=>c.id===id).text.includes('annual repayments'));
});
