import test from 'node:test';
import assert from 'node:assert/strict';
async function api(){const m=await import('../lib/research/review-calibration.mjs').catch(e=>{if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;return {}});assert.equal(typeof m.prepareCalibration,'function','calibration must have an executable input boundary');return m;}
const dossier={ticker:'TEST',sections:[{extracts:[{id:'D1:1',text:'The company sells devices. It may repurchase shares but has no minimum obligation.'}]}]};
const cases=[{id:'faithful',chunkId:'D1:1',text:'The company may repurchase shares.',expected:true,requiredSupport:['may repurchase shares']},{id:'overreach',chunkId:'D1:1',text:'The company must repurchase shares.',expected:false,requiredSupport:[]}];
test('calibration keeps labels out of the model packet and rejects an all-rejected shortcut',async()=>{
 const m=await api(),prepared=m.prepareCalibration([{dossier,cases}]);
 assert.ok(!JSON.stringify(prepared.packet).includes('expected'));
 assert.ok(!JSON.stringify(prepared.packet).includes('requiredSupport'));
 assert.ok(!JSON.stringify(prepared.packet).includes('faithful'),'case names must not leak the expected verdict');
 const r=m.evaluateCalibration({reviews:prepared.packet.claims.map(c=>({id:c.id,verdict:'unsupported',unsupportedClause:'Not supported.',supportIds:[]}))},prepared);
 assert.equal(r.passed,false);assert.equal(r.falsePositives,0);assert.equal(r.falseNegatives,1);
 assert.equal(r.qualityCertified,false);
});
test('accepting all claims fails, even with real source references',async()=>{
 const m=await api(),p=m.prepareCalibration([{dossier,cases}]);
 const r=m.evaluateCalibration({reviews:p.packet.claims.map(c=>({id:c.id,verdict:'supported',unsupportedClause:'',supportIds:[p.packet.sources[0].spans[0].id]}))},p);
 assert.equal(r.falsePositives,1);assert.equal(r.passed,false);
});

test('a provenance rejection cannot disguise an incorrect model approval as successful calibration',async()=>{
 const m=await api(),p=m.prepareCalibration([{dossier,cases}]);
 const raw={reviews:p.packet.claims.map((c,i)=>({id:c.id,verdict:'supported',unsupportedClause:'',supportIds:i?['invented']:[p.packet.sources[0].spans[0].id]}))};
 const r=m.evaluateCalibration(raw,p);
 assert.equal(r.passed,false,'the model approved an unsupported claim even though a separate gate saved publication');
 assert.equal(r.falsePositives,0,'pipeline false approvals remain separate');
 assert.equal(r.modelFalsePositives,1);assert.equal(r.blockedModelFalsePositives,1);
 assert.equal(r.modelFalseNegatives,0);
});

test('model abstention and reference failure remain distinguishable for supported claims',async()=>{
 const m=await api(),p=m.prepareCalibration([{dossier,cases}]);
 const rows=p.packet.claims.map(c=>({id:c.id,verdict:'uncertain',unsupportedClause:'Uncertain.',supportIds:[]}));
 let r=m.evaluateCalibration({reviews:rows},p);
 assert.equal(r.modelFalseNegatives,1);assert.equal(r.modelUncertain,2);
 rows[0]={...rows[0],verdict:'supported',unsupportedClause:''};
 r=m.evaluateCalibration({reviews:rows},p);
 assert.equal(r.modelFalseNegatives,0);assert.equal(r.falseNegatives,1);assert.equal(r.passed,false);
});
test('right verdicts with a heading-only reference do not pass support coverage',async()=>{
 const m=await api(),d=structuredClone(dossier);d.sections[0].extracts[0].text='A long and irrelevant heading about business.\nThe company may repurchase shares.';
 const p=m.prepareCalibration([{dossier:d,cases}]);
 const r=m.evaluateCalibration({reviews:p.packet.claims.map((c,i)=>({id:c.id,verdict:i?'unsupported':'supported',unsupportedClause:i?'must':'',supportIds:i?[]:[p.packet.sources[0].spans[0].id]}))},p);
 assert.equal(r.falsePositives,0);assert.equal(r.falseNegatives,0);assert.equal(r.supportFailures,1);assert.equal(r.passed,false);
});
test('cross-company source identities remain distinct and incomplete review cannot pass',async()=>{
 const m=await api(),other={...dossier,ticker:'OTHER'};const p=m.prepareCalibration([{dossier,cases},{dossier:other,cases}]);
 assert.equal(new Set(p.packet.sources.map(s=>s.chunkId)).size,2);
 assert.throws(()=>m.evaluateCalibration({reviews:[]},p),/INVALID_REFERENCE_REVIEW/);
 assert.throws(()=>m.prepareCalibration([{dossier,cases:[{...cases[0],requiredSupport:['not in the source']}]}]),/INVALID_CALIBRATION/);
});

test('calibration preserves every source of an actual multi-source claim',async()=>{
 const m=await api(),d=structuredClone(dossier);d.sections[0].extracts.push({id:'D2:1',text:'Cash was used for repurchases. Other cash was generated by operations.'});
 const c={id:'linked',chunkIds:['D1:1','D2:1'],text:'Repurchases were optional and the cash statement reports repurchase payments.',expected:true,requiredSupport:['no minimum obligation','Cash was used for repurchases']};
 const p=m.prepareCalibration([{dossier:d,cases:[c]}]);
 assert.deepEqual(p.packet.claims[0].chunkIds,['TEST:D1:1','TEST:D2:1']);
 assert.equal(p.packet.sources.length,2);
 const raw={reviews:[{id:'c0',verdict:'supported',unsupportedClause:'',supportIds:[p.packet.sources[0].spans[0].id]}]};
 assert.equal(m.evaluateCalibration(raw,p).passed,false);
 raw.reviews[0].supportIds.push(p.packet.sources[1].spans[0].id);
 assert.equal(m.evaluateCalibration(raw,p).passed,true);
 for(const chunkIds of [[],['D1:1','D1:1'],['D1:1','missing']])assert.throws(()=>m.prepareCalibration([{dossier:d,cases:[{...c,chunkIds}]}]),/INVALID_CALIBRATION/);
 assert.throws(()=>m.prepareCalibration([{dossier:d,cases:[{...c,chunkId:'D1:1'}]}]),/INVALID_CALIBRATION/);
 assert.throws(()=>m.prepareCalibration([{dossier:d,cases:[{...c,chunkIds:['D1:1']}]}]),/INVALID_CALIBRATION/);
});
