const copy = (es, en) => Object.freeze({ es, en });

const option = (value, labelEs, labelEn, descriptionEs, descriptionEn) =>
  Object.freeze({
    value,
    label: copy(labelEs, labelEn),
    description: copy(descriptionEs, descriptionEn),
  });

export const CHANNEL_QUESTIONS = Object.freeze([
  Object.freeze({
    id: "archetypes",
    type: "multi",
    required: true,
    maxSelections: 3,
    prompt: copy(
      "¿En qué contextos tienes una capacidad repetida para observar e interpretar cambios?",
      "In which settings can you repeatedly observe and interpret change?",
    ),
    help: copy(
      "Elige hasta tres. Buscamos posibles canales de investigación, no acciones ni una ventaja ya demostrada.",
      "Choose up to three. We are looking for possible research channels, not stocks or a proven edge.",
    ),
    options: Object.freeze([
      option(
        "professional_workflow",
        "Flujo profesional",
        "Professional workflow",
        "Conoces de primera mano cómo se adopta, usa o reemplaza una herramienta en un trabajo.",
        "You know firsthand how a tool is adopted, used, or replaced in a professional workflow.",
      ),
      option(
        "local_geographic",
        "Contexto local o geográfico",
        "Local or geographic context",
        "Puedes observar patrones públicos de adopción, precios o actividad en un lugar específico.",
        "You can observe public adoption, pricing, or activity patterns in a specific place.",
      ),
      option(
        "public_records",
        "Registros públicos",
        "Public records",
        "Sabes encontrar y relacionar datos abiertos, permisos, registros o documentos regulatorios.",
        "You know how to find and connect open data, permits, registries, or regulatory documents.",
      ),
      option(
        "procurement",
        "Compras y licitaciones públicas",
        "Public procurement",
        "Entiendes presupuestos, adjudicaciones y ciclos de compra disponibles para cualquier persona.",
        "You understand budgets, awards, and purchasing cycles available to any member of the public.",
      ),
      option(
        "technical_product",
        "Producto técnico",
        "Technical product",
        "Puedes evaluar documentación, arquitectura, rendimiento o fricción de un producto complejo.",
        "You can assess documentation, architecture, performance, or friction in a complex product.",
      ),
      option(
        "regulated_economics",
        "Economía regulada",
        "Regulated economics",
        "Comprendes cómo reglas públicas cambian precios, reembolsos, capacidad o incentivos.",
        "You understand how public rules change prices, reimbursement, capacity, or incentives.",
      ),
      option(
        "public_supply_chain",
        "Cadena de suministro pública",
        "Public supply chain",
        "Sigues precios, inventarios, plazos o cuellos de botella mediante fuentes públicas.",
        "You track prices, inventories, lead times, or bottlenecks through public sources.",
      ),
      option(
        "consumer_behavior",
        "Comportamiento del consumidor",
        "Consumer behavior",
        "Observas cambios repetidos y agregados en uso, preferencia, disponibilidad o precio.",
        "You observe repeated, aggregated changes in usage, preference, availability, or price.",
      ),
    ]),
  }),
  Object.freeze({
    id: "direct_experience",
    type: "single",
    required: true,
    prompt: copy(
      "¿Cuánta experiencia directa y repetida tienes en esos contextos?",
      "How much direct, repeated experience do you have in those settings?",
    ),
    help: copy(
      "La experiencia cuenta solo si mejora tu capacidad para distinguir un cambio real de una impresión casual.",
      "Experience counts only when it helps you distinguish a real change from a casual impression.",
    ),
    options: Object.freeze([
      option(
        "none",
        "Ninguna experiencia directa",
        "No direct experience",
        "Mi conocimiento proviene principalmente de noticias o comentarios generales.",
        "My knowledge comes mainly from news or general commentary.",
      ),
      option(
        "occasional",
        "Contacto ocasional",
        "Occasional exposure",
        "Lo veo algunas veces, pero no con una rutina estable.",
        "I encounter it sometimes, but not through a stable routine.",
      ),
      option(
        "repeated",
        "Experiencia repetida",
        "Repeated experience",
        "Lo observo de manera consistente y puedo comparar cambios a través del tiempo.",
        "I observe it consistently and can compare changes over time.",
      ),
      option(
        "operator",
        "Usuario u operador experto",
        "Expert user or operator",
        "He tomado decisiones recurrentes en este flujo y conozco sus restricciones prácticas.",
        "I have made recurring decisions in this workflow and know its practical constraints.",
      ),
    ]),
  }),
  Object.freeze({
    id: "source_safety",
    type: "single",
    required: true,
    prompt: copy(
      "¿Puedes investigar este posible canal usando exclusivamente información pública y observaciones permitidas?",
      "Can you research this possible channel using only public information and permitted observations?",
    ),
    help: copy(
      "No ingreses datos ni detalles. Si depende de información interna, de pacientes o de clientes, el diagnóstico se detiene.",
      "Do not enter data or details. If it depends on internal, patient, or client information, the assessment stops.",
    ),
    options: Object.freeze([
      option(
        "public_safe",
        "Sí, solo información pública y permitida",
        "Yes, public and permitted information only",
        "Puedo formular y verificar la hipótesis sin usar información confidencial o restringida.",
        "I can form and test the hypothesis without confidential or restricted information.",
      ),
      option(
        "unsure",
        "No estoy seguro",
        "I am not sure",
        "Necesito revisar los límites antes de continuar.",
        "I need to review the boundaries before continuing.",
      ),
      option(
        "internal_private",
        "Depende de información interna o privada",
        "It depends on internal or private information",
        "Este origen no puede usarse en el diagnóstico.",
        "This source cannot be used in the assessment.",
      ),
      option(
        "patient",
        "Incluye información de pacientes",
        "It includes patient information",
        "Los datos clínicos o de pacientes no pueden usarse aquí.",
        "Clinical or patient data cannot be used here.",
      ),
      option(
        "client",
        "Incluye información de clientes",
        "It includes client information",
        "Los datos confidenciales de clientes no pueden usarse aquí.",
        "Confidential client data cannot be used here.",
      ),
    ]),
  }),
  Object.freeze({
    id: "public_sources",
    type: "multi",
    required: true,
    maxSelections: 3,
    prompt: copy(
      "¿Qué fuentes podrían comprobar tus observaciones sin revelar información restringida?",
      "Which sources could verify your observations without revealing restricted information?",
    ),
    help: copy(
      "Elige hasta tres fuentes. Marca una categoría restringida si no puedes verificar el canal solo con material público.",
      "Choose up to three sources. Select a restricted category if the channel cannot be tested with public material alone.",
    ),
    options: Object.freeze([
      option(
        "public_filings",
        "Filings y reportes públicos",
        "Public filings and reports",
        "Estados, presentaciones y reportes publicados por emisores o reguladores.",
        "Statements, presentations, and reports published by issuers or regulators.",
      ),
      option(
        "government_records",
        "Registros gubernamentales abiertos",
        "Open government records",
        "Permisos, licitaciones, presupuestos, estadísticas y bases abiertas.",
        "Permits, tenders, budgets, statistics, and open databases.",
      ),
      option(
        "public_prices",
        "Precios y catálogos públicos",
        "Public prices and catalogs",
        "Precios visibles, disponibilidad, inventario publicado o catálogos abiertos.",
        "Visible prices, availability, published inventory, or open catalogs.",
      ),
      option(
        "product_docs",
        "Documentación pública de producto",
        "Public product documentation",
        "Notas de versión, manuales, especificaciones, ofertas laborales o repositorios abiertos.",
        "Release notes, manuals, specifications, job postings, or open repositories.",
      ),
      option(
        "public_observation",
        "Observación pública agregada",
        "Aggregated public observation",
        "Patrones visibles en tiendas, sitios o servicios, sin datos personales ni acceso restringido.",
        "Patterns visible in stores, sites, or services, without personal data or restricted access.",
      ),
      option(
        "internal_private",
        "Información interna o privada",
        "Internal or private information",
        "Fuente restringida: el diagnóstico debe detenerse.",
        "Restricted source: the assessment must stop.",
      ),
      option(
        "patient",
        "Información de pacientes",
        "Patient information",
        "Fuente restringida: el diagnóstico debe detenerse.",
        "Restricted source: the assessment must stop.",
      ),
      option(
        "client",
        "Información de clientes",
        "Client information",
        "Fuente restringida: el diagnóstico debe detenerse.",
        "Restricted source: the assessment must stop.",
      ),
      option(
        "none",
        "Aún no tengo una fuente pública",
        "I do not yet have a public source",
        "La observación todavía no puede verificarse de forma independiente.",
        "The observation cannot yet be independently verified.",
      ),
    ]),
  }),
  Object.freeze({
    id: "repeatability",
    type: "single",
    required: true,
    prompt: copy(
      "¿Con qué frecuencia podrías repetir la misma observación de forma comparable?",
      "How often could you repeat the same observation on a comparable basis?",
    ),
    help: copy(
      "Un canal necesita una serie de observaciones; un caso llamativo por sí solo no alcanza.",
      "A channel needs a series of observations; one striking case is not enough.",
    ),
    options: Object.freeze([
      option(
        "one_off",
        "Fue una observación única",
        "It was a one-off observation",
        "No tengo una forma estable de repetirla.",
        "I do not have a stable way to repeat it.",
      ),
      option(
        "quarterly",
        "Trimestral o menos",
        "Quarterly or less often",
        "Puedo revisarla algunas veces al año con criterios similares.",
        "I can review it a few times per year using similar criteria.",
      ),
      option(
        "monthly",
        "Mensual",
        "Monthly",
        "Puedo producir una observación comparable cada mes.",
        "I can produce a comparable observation each month.",
      ),
      option(
        "weekly",
        "Semanal",
        "Weekly",
        "Puedo observarla semanalmente sin convertirla en una carga inviable.",
        "I can observe it weekly without making it an unsustainable burden.",
      ),
    ]),
  }),
  Object.freeze({
    id: "issuer_kpi_mapping",
    type: "single",
    required: true,
    prompt: copy(
      "¿Puedes conectar la observación con un emisor y una variable económica verificable?",
      "Can you connect the observation to an issuer and a verifiable economic variable?",
    ),
    help: copy(
      "La conexión debe explicar qué KPI podría cambiar y en qué dirección, no solo nombrar una empresa.",
      "The link should explain which KPI may change and in what direction, not merely name a company.",
    ),
    options: Object.freeze([
      option(
        "none",
        "No veo una conexión económica",
        "I do not see an economic link",
        "La observación es interesante, pero no sé quién captura su efecto.",
        "The observation is interesting, but I do not know who captures its effect.",
      ),
      option(
        "issuer_only",
        "Puedo nombrar emisores expuestos",
        "I can name exposed issuers",
        "Veo qué empresas participan, pero aún no el KPI relevante.",
        "I can see which companies participate, but not yet the relevant KPI.",
      ),
      option(
        "issuer_kpi",
        "Emisor y KPI identificados",
        "Issuer and KPI identified",
        "Puedo proponer una cadena causal hacia volumen, precio, margen, retención o capital.",
        "I can propose a causal chain to volume, price, margin, retention, or capital.",
      ),
      option(
        "issuer_kpi_timing",
        "Emisor, KPI y ventana temporal",
        "Issuer, KPI, and timing window",
        "Puedo decir qué variable debería moverse y cuándo podría aparecer públicamente.",
        "I can state which variable should move and when it may appear publicly.",
      ),
    ]),
  }),
  Object.freeze({
    id: "testability",
    type: "single",
    required: true,
    prompt: copy(
      "¿Qué tan falsable puede ser tu hipótesis antes de mirar el resultado?",
      "How falsifiable can your hypothesis be before you see the outcome?",
    ),
    help: copy(
      "Una buena prueba registra de antemano la dirección, el plazo y qué evidencia la rechazaría.",
      "A useful test records the direction, time window, and rejection evidence in advance.",
    ),
    options: Object.freeze([
      option(
        "narrative",
        "Solo puedo contar una historia",
        "I can only tell a story",
        "No tengo una predicción que pueda fallar de manera clara.",
        "I do not have a prediction that can clearly fail.",
      ),
      option(
        "directional",
        "Puedo predecir una dirección",
        "I can predict a direction",
        "Puedo anticipar mejora o deterioro, pero sin un plazo preciso.",
        "I can anticipate improvement or deterioration, but without a precise time window.",
      ),
      option(
        "dated_falsifier",
        "Puedo fijar plazo y falsificador",
        "I can set a date and falsifier",
        "Puedo escribir antes de tiempo qué debería ocurrir y qué invalidaría la idea.",
        "I can write in advance what should happen and what would invalidate the idea.",
      ),
      option(
        "repeated_predictions",
        "Puedo repetir predicciones comparables",
        "I can repeat comparable predictions",
        "Puedo registrar una serie de pruebas ex ante y luego medir calibración y errores.",
        "I can log a series of ex-ante tests and later measure calibration and errors.",
      ),
    ]),
  }),
  Object.freeze({
    id: "protection_time_fit",
    type: "single",
    required: true,
    prompt: copy(
      "¿Por qué otros podrían pasar por alto la señal y puedes observarla con el tiempo disponible?",
      "Why might others overlook the signal, and can you observe it with the time you have?",
    ),
    help: copy(
      "La protección válida proviene de trabajo, contexto o interpretación especializada sobre fuentes públicas, nunca de acceso confidencial.",
      "Valid protection comes from work, context, or specialized interpretation of public sources, never confidential access.",
    ),
    options: Object.freeze([
      option(
        "none",
        "No veo protección ni una rutina viable",
        "I see no protection or viable routine",
        "La observación es obvia para todos o no puedo mantenerla.",
        "The observation is obvious to everyone or I cannot sustain it.",
      ),
      option(
        "attention_fit",
        "Trabajo público tedioso, con tiempo suficiente",
        "Tedious public work, with enough time",
        "Requiere recopilar y normalizar material público que pocos siguen con constancia.",
        "It requires collecting and normalizing public material that few people follow consistently.",
      ),
      option(
        "specialized_fit",
        "Interpretación especializada, con tiempo suficiente",
        "Specialized interpretation, with enough time",
        "El material es público, pero interpretarlo exige experiencia que ya poseo.",
        "The material is public, but interpreting it requires expertise I already have.",
      ),
      option(
        "local_fit",
        "Contexto local público, con tiempo suficiente",
        "Public local context, with enough time",
        "Puedo combinar señales públicas locales que otros inversionistas no monitorean de cerca.",
        "I can combine public local signals that other investors do not monitor closely.",
      ),
      option(
        "protected_low_time",
        "Hay una barrera válida, pero poco tiempo",
        "There is a valid barrier, but little time",
        "La interpretación puede ser diferencial, aunque mi capacidad de mantener la rutina es limitada.",
        "The interpretation may be differentiated, but my ability to maintain the routine is limited.",
      ),
    ]),
  }),
]);
