import { expect, test } from '@playwright/test';
test.skip(process.env.BLS_READING_FIXTURE_SERVER !== '1', 'Requires the isolated local QA provider, never production data.');

const labels = ['Crecimiento inicial de ingresos', 'Margen operativo', 'Reinversión neta / NOPAT', 'Tasa de descuento (WACC)', 'Crecimiento terminal', 'Impuesto normalizado', 'ROIC terminal', 'Dilución anual'];
const policy = { central: [12, 20, 25, 10, 2, 25, 15, .5], adverse: [5, 15, 40, 12, 1, 25, 12, 1], favorable: [20, 25, 20, 9, 2.5, 25, 18, .2] };
test('covered generic issuer requires declared hypotheses, recalculates, narrates and commits identical server results', async ({ page }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/company/SYNTH/thesis?lang=es');
  await expect(page.getByRole('heading', { name: 'Synthetic QA Company', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'No se publica rango ni impacto en cartera.' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Fijar esta versión' })).toBeDisabled();
  await expect(page.getByLabel('Tasa de descuento (WACC) · central', { exact: true })).toHaveValue('');
  for (const [scenario, values] of Object.entries(policy)) for (let i = 0; i < labels.length; i++) await page.getByLabel(`${labels[i]} · ${scenario}`, { exact: true }).fill(String(values[i]));
  await page.getByLabel('Fundamento y evidencia que lo refutaría').fill('Hipótesis sintéticas de QA. Un margen inferior al declarado refutaría el criterio.');
  await page.getByRole('button', { name: 'Aplicar hipótesis y recalcular' }).click();
  await expect(page.getByRole('heading', { name: 'Cuánto vale bajo estas hipótesis' })).toBeVisible();
  const interpretation = page.getByRole('group', { name: '¿Qué representa el crecimiento implícito?' });
  await interpretation.getByLabel('Una predicción del crecimiento que ocurrirá').check();
  await expect(interpretation).toContainText('Revisa esta interpretación');
  await interpretation.getByLabel('Una condición del modelo al mantener los demás supuestos').check();
  await expect(interpretation).toContainText('Interpretación compatible');
  const run = await page.getByTestId('company-thesis').getAttribute('data-run-id');
  await page.getByRole('button', { name: 'Ver y escuchar la lectura' }).click();
  await expect(page.getByTestId('snapshot-player')).toHaveAttribute('data-run-id', run);
  const saveRequest = page.waitForRequest(r => r.url().includes('/api/public/company-thesis/SYNTH') && r.method() === 'POST');
  await page.getByRole('button', { name: 'Fijar esta versión' }).click();
  const savedBody = (await saveRequest).postDataJSON();
  await expect(page.getByTestId('frozen-version')).toContainText(run);
  const forged = await page.request.post('/api/public/company-thesis/SYNTH', { headers: { Origin: new URL(page.url()).origin }, data: { ...savedBody, expectedVersion: 1, runId: 'forged-client-result', valuation: { central: 999999 } } });
  expect(forged.status()).toBe(409);
  await expect(page.getByTestId('frozen-version')).toContainText('2027-06-30');
  await page.getByRole('button', { name: 'Ensayar menor crecimiento y conversión' }).click();
  await expect(page.getByTestId('thesis-conclusions').getByText('Deja de sostenerse')).toHaveCount(3);
  await expect(page.getByTestId('snapshot-player')).not.toHaveAttribute('data-run-id', run);
  await page.getByRole('button', { name: 'Buscar y añadir evidencia posterior' }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'Aún no hay un cierre anual posterior' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  expect(errors).toEqual([]);
});
test('searching another issuer resolves its method and preserves abstention for banks', async ({ page }) => {
  await page.goto('/company/SYNTH/thesis');
  await page.getByLabel('Empresa a investigar').fill('SYNBANK');
  await page.getByRole('button', { name: 'Investigar empresa' }).click();
  await expect(page).toHaveURL(/\/company\/SYNBANK\/thesis/);
  await expect(page.getByLabel('Cobertura y método')).toContainText('residual_income');
  await expect(page.getByRole('heading', { name: 'No se publica rango ni impacto en cartera.' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Aplicar hipótesis y recalcular' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Fijar esta versión' })).toBeDisabled();
});
