import {test,expect} from './filing-test-fixtures.mjs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const dossier=require('../lib/research/published/MSFT.json');
test.beforeEach(()=>test.skip(!process.env.BLS_E2E_AUTHENTICATED,'Local authenticated QA only'));
test('revenue drivers reconcile without AI and retain source links across separate views',async({page})=>{
 const errors=[];let aiCalls=0;
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/public/research?ticker=MSFT',r=>r.fulfill({json:{dossier,ticket:'test-ticket',analysisAvailable:false}}));
 await page.route('**/api/research/financial-reading',r=>r.fulfill({status:503,json:{error:'FINANCIAL_SOURCE_UNAVAILABLE'}}));
 await page.route('**/api/research/theses?ticker=*',r=>r.fulfill({json:{revisions:[]}}));
 await page.route('**/api/public/research/analyze',r=>{aiCalls++;return r.abort()});
 await page.goto('/research?ticker=MSFT&lang=es');
 await page.getByText('Desglose completo de ingresos',{exact:true}).click();
 const panel=page.locator('[data-revenue-breakdown]');
 await expect(panel.getByRole('heading',{name:'De dónde viene el crecimiento'})).toBeVisible();
 await expect(panel.locator('li')).toHaveCount(10);
 const row=panel.locator('li').filter({hasText:'Server products and cloud services'});
 await expect(row.locator('summary')).toContainText('+11,00 pp');
 await row.locator('summary').click();
 const source=dossier.sources.find(s=>s.id===dossier.revenueBreakdown.sourceId);
 const fact=dossier.revenueBreakdown.partitions[0].rows[0].current;
 await expect(row.getByRole('link',{name:'Cifra actual en el documento'})).toHaveAttribute('href',`${source.url}#${encodeURIComponent(fact.factId)}`);
 await panel.getByText('Conciliación y alcance',{exact:true}).click();
 await expect(panel.getByText('Las filas cuadran con los ingresos consolidados en ambos períodos.',{exact:true})).toBeVisible();
 await panel.getByRole('button',{name:'Segmentos',exact:true}).click();
 await expect(panel.locator('li')).toHaveCount(3);
 await expect(panel.locator('summary').filter({hasText:'More Personal Computing'})).toContainText('−0,21 pp');
 await panel.getByRole('button',{name:'Geografía',exact:true}).click();
 await expect(panel.locator('li')).toHaveCount(2);
 expect(aiCalls).toBe(0);expect(errors).toEqual([]);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
